on:
  pull_request:
    types: [opened, synchronize, reopened]
name: Test Website Generation
jobs:
  build:
    name: Test Website Generation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup Ruby for use with actions
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # or your preferred version
          bundler-cache: true # This replaces the manual cache step!
      - name: Build website
        run: |
          bundle exec jekyll build -d _site/
